### ISSUE TITLE
Add zero when the value is less than 10 (1 -> 01 etc.) ?

### ISSUE THREAD

**Issue by pelemele01** [StephenVinouze/MaterialNumberPicker#11]
Bojour,

Serait-il possible d'avoir 2 chiffres si la valeur est inférieur à 10 (1 -> 01 etc.) ? 
Et merci pour cette librairie ^^

**Comment by StephenVinouze** [comment]
Bonjour,
vous avez un formatter disponible donc rien ne vous empêche de formatter votre valeur comme bon vous semble ;)

**Comment by pelemele01** [comment]
Bonjour,
ha, parfait, je n'avais pas vu ça.
Merci beaucoup ^^
