### ISSUE TITLE
Which version is it?

### ISSUE THREAD

**Issue by Frank-99** [StephenVinouze/MaterialNumberPicker#14]
`implementation 'com.github.StephenVinouze:MaterialNumberPicker:1.1.0'`

I managed to find this working version, but I'm not sure if it's the last one available...
could you specify the current version in the README file?

or maybe I'm missing something? I'm not an expert on android studio, especially with dependencies, so maybe it just flew over my head...

**Comment by StephenVinouze** [comment]
It is the 1.1.0. It is actually specified in the readme with the jetpack badge. You can also find the latest tag version in the github's release section
