### ISSUE TITLE
Issue with font size

### ISSUE THREAD

**Issue by githubashutoshsoni** [StephenVinouze/MaterialNumberPicker#18]
I'm using fontsize as 32sp. On a oneplus 6. Android Q. Stable. But the font size is not changing at all. I tried app:mnpTextSize="32sp" and also    materialNumberPicker.setTextSize(32); but no luck. Can you please check it? thanks!

**Comment by githubashutoshsoni** [comment]
I tested on an emulator but it worked. Not on my oneplus 6.

**Comment by StephenVinouze** [comment]
no problem on my side, if you have more info don't hesitate to reopen the issue ;)
