### ISSUE TITLE
How do I set a range

### ISSUE THREAD

**Issue by githubashutoshsoni** [StephenVinouze/MaterialNumberPicker#19]
like a minimum range of 5. So the next values will be 5, 10,15,20,25,30,35 in the number picker.

**Comment by StephenVinouze** [comment]
This library, same as native number picker, take a min and max value. But nothing prevent you from using the formatter and format your text. The format is easy: in your example above you would have minValue = 1 and maxValue = 7, your formatter is `value * 5`
