### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by Rainer-Lang** [StephenVinouze/MaterialNumberPicker#4]
I'm not using Kotlin right now. How could I use this lib with Java?

**Comment by StephenVinouze** [comment]
Excellent question @Rainer-Lang => you should use Kotlin, it's so much fun compared to old Java ;)
More seriously, I didn't think about it, my constructor was not fit for Java, my mistake. I'm fixing it right now and got it working. I'm adding a duplication of the sample module in Java to have the dual setup, and will provide an explanation in the README as well ;)

**Comment by Rainer-Lang** [comment]
@StephenVinouze You're so kind. Thank you very much.
I was considering to use Kotlin too, but right now I have so many other things to do. :-(

**Comment by StephenVinouze** [comment]
You're good to go. Version `1.0.4` includes Java interop and I updated the README ;)
