### ISSUE TITLE
Constructor default for wrapped is DEFAULT_EDITABLE

### ISSUE THREAD

**Issue by rocca23** [StephenVinouze/MaterialNumberPicker#6]
As per title, the default for the `wrapped` constructor argument is `DEFAULT_EDITABLE` instead of `DEFAULT_WRAPPED`. Just a minor bug, since actually they're both `false` and the default behavior is eventually working as intended.

**Comment by StephenVinouze** [comment]
That's indeed a bad copy/paste, thanks for noticing it :)
Will be fixing it soon and take advantage to upgrade lib dependencies/Kotlin version as well ;)

**Comment by roccadev** [comment]
You're welcome. Thanks for your work by the way, and thanks for using Kotlin ;)

**Comment by StephenVinouze** [comment]
The fixed has been included in `1.0.6` ;)
