### ISSUE TITLE
Show more than 3 values

### ISSUE THREAD

**Issue by tayaza** [StephenVinouze/MaterialNumberPicker#7]
Hello, 
Thanks for putting out such a great work. I'd like to display about 10 items (instead of 3) at once on the picker.  Please kindly advise on how to implement that. I am using Java. Thank you.

**Comment by StephenVinouze** [comment]
Hi,
I'm not sure to understand what you're trying to achieve. Could you please provide me more details? A basic image would be even better

**Comment by kazimad** [comment]
I think than question is - does you library can show more than 3 elements, maybe 5 or more ?

**Comment by StephenVinouze** [comment]
It takes a number of items equals to `maxItems` so yes it's possible. But I thought they was more behind the question
