### ISSUE TITLE
Request: Increase density of numbers shown on picker

### ISSUE THREAD

**Issue by TheIronMarx** [StephenVinouze/MaterialNumberPicker#8]
Hello! 

I would like to be able to have the option to set a density of the number of items displayed in the picker. The AOSP default `NumberPicker` also shows three at a time, but this feels too loose or sparse for some UI preferences. 

I believe this is also what #7 was asking for as well.

![screen shot 2018-07-12 at 1 10 01 pm](https://user-images.githubusercontent.com/3372405/42651513-39d123d2-85d5-11e8-86ed-164c07cf1449.png)
The above image shows the iOS analogy to Android's `NumberPicker`.

**Comment by StephenVinouze** [comment]
Hi @TheIronMarx 
There is unfortunately no way to this without copying the whole `NumberPicker` class and extend this library class from it as it is declared as a private static int inside the native class.
I could obviously do some reflection to retrieve the parameter but it won't change the setup of the items that depends on this parameter...
This investigation didn't go to waste as I profited from this moment to upgrade kotlin and clean a bit the library to release a patch version `1.0.7`
