### ISSUE TITLE
Two NumberPicker in one Alert

### ISSUE THREAD

**Issue by Racine2Ju** [StephenVinouze/MaterialNumberPicker#9]
Hello!

First of all, thank you for this library!
I'm trying to make an picker alert but with two numberPickers (for exemple to choose the weight with the kilos and the grammes after), but can't find the way to do it.
I've tried to change the function presentPickerInAlert with two NumberPickers but cound't find how to set 2 views. 
Can you help me with that?
Thank you

**Comment by StephenVinouze** [comment]
You can build a custom view in which you insert two number pickers. I'm not sure how it will behave inside a dialog with scrolling but that's more a UX issue ;)
